### PR TITLE
Remove support for non DC

### PR DESCRIPTION
**Pull request by richardhallett**
This removes the support for lookup of non DataCite formats i.e. Crossref

This is a feature change but it's not working properly for Crossref currently.

This can not be merged until final decision is made from product perspective, but just to check I'm not missing something obvious

### CODE REVIEW

**Review by digitaldogsbody — COMMENTED** [review]
Could we possibly refactor to keep the support for mEDRA and JaLC DOIs (i.e del 17-24, keep 25-37) or are they so few of the requests that it's not worth keeping?

**Comment by richardhallett** [comment]
Not worth it imo, plus also I think fundamentally it's weird to come to us for this rather than directly going via doi.org

**Comment by digitaldogsbody** [comment]
:+1: makes sense to me. The use-case would be that some users find our CSL-JSON better than that of other RA's CN services (see https://github.com/crosscite/content-negotiation/issues/104#issuecomment-1017116334 & https://github.com/crosscite/content-negotiation/issues/104#issuecomment-1020171265) but given that the majority of those requests would be for CrossRef, I think encouraging the users to go via doi.org and take up the non-DataCite DOI output issues with the respective RAs is a perfectly acceptable approach.

**Comment by richardhallett** [comment]
Yes it is true there is a possibility that our response based on our library that converts could indeed be "better" or at least more useful for certain people. And it's unfortunate, I think for the most part this is affecting Crossref DOIs and as it stands this isn't working at all right now.

I think it's something we should encourage to go via doi.org and work with other RAs.

Additionally the CSL json returned is based on metadata and a third party libraries so it's not beyond question to do something themselves, though granted that's a more complicated workflow.

**Pull request merged**
